//
//  InitData.m
//  SoundValley
//
//  Created by apple on 2020/5/10.
//  Copyright © 2020 apple. All rights reserved.
//

#import "InitData.h"

@implementation InitData
+(NSArray *)getSceneListData{
    NSString *path = [[NSBundle mainBundle]pathForResource:@"voice" ofType:@"bundle"];
    return  @[
            @{@"icon":@"cjhbl",
                @"title":@"船桨和波浪",
                @"bigIcon":@"cjhbl",
                @"voice":[[NSBundle bundleWithPath:path]pathForResource:@"船桨和波浪" ofType:@"mp3"]},
             @{@"icon":@"xgyw",
               @"title":@"峡谷夜晚",
               @"bigIcon":@"xgyw",
               @"voice":[[NSBundle bundleWithPath:path]pathForResource:@"峡谷夜晚" ofType:@"mp3"]},
             @{@"icon":@"zl",
               @"title":@"竹林",
               @"bigIcon":@"zl",
               @"voice":[[NSBundle bundleWithPath:path]pathForResource:@"竹林" ofType:@"mp3"]},
             @{@"icon":@"hbmw",
               @"title":@"湖边木屋",
               @"bigIcon":@"hbmw",
               @"voice":[[NSBundle bundleWithPath:path]pathForResource:@"湖边木屋" ofType:@"mp3"]},
            @{@"icon":@"jbgh",
              @"title":@"江边篝火",
              @"bigIcon":@"jbgh",
              @"voice":[[NSBundle bundleWithPath:path]pathForResource:@"江边篝火" ofType:@"mp3"]},
            @{@"icon":@"xgpb",
              @"title":@"峡谷瀑布",
              @"bigIcon":@"xgpb",
              @"voice":[[NSBundle bundleWithPath:path]pathForResource:@"峡谷瀑布" ofType:@"mp3"],
              @"index":@0},
                       @{@"icon":@"hmfl",
                         @"title":@"湖面风浪",
                         @"bigIcon":@"hmfl",
                         @"voice":[[NSBundle bundleWithPath:path]pathForResource:@"湖面风浪" ofType:@"mp3"]},
                       @{@"icon":@"tyzc",
                         @"title":@"田野早晨",
                         @"bigIcon":@"tyzc",
                         @"voice":[[NSBundle bundleWithPath:path]pathForResource:@"田野早晨" ofType:@"mp3"]},
                       @{@"icon":@"zly",
                         @"title":@"棕榈叶",
                         @"bigIcon":@"zly",
                         @"voice":[[NSBundle bundleWithPath:path]pathForResource:@"棕榈叶" ofType:@"mp3"]},
                       @{@"icon":@"smxw",
                         @"title":@"水面漩涡",
                         @"bigIcon":@"smxw",
                         @"voice":[[NSBundle bundleWithPath:path]pathForResource:@"水面漩涡" ofType:@"mp3"]},
                       @{@"icon":@"habyq",
                         @"title":@"河岸边鸭群",
                         @"bigIcon":@"habyq",
                         @"voice":[[NSBundle bundleWithPath:path]pathForResource:@"河岸边鸭群" ofType:@"mp3"]},
                       @{@"icon":@"hbly",
                         @"title":@"海边雷雨",
                         @"bigIcon":@"hbly",
                         @"voice":[[NSBundle bundleWithPath:path]pathForResource:@"海边雷雨" ofType:@"mp3"]},
                       @{@"icon":@"sl",
                         @"title":@"树林",
                         @"bigIcon":@"sl",
                         @"voice":[[NSBundle bundleWithPath:path]pathForResource:@"树林" ofType:@"mp3"]},
                       @{@"icon":@"cc",
                         @"title":@"草丛",
                         @"bigIcon":@"cc",
                         @"voice":[[NSBundle bundleWithPath:path]pathForResource:@"草丛" ofType:@"mp3"]},
                       @{@"icon":@"sjxl",
                         @"title":@"山间溪水",
                         @"bigIcon":@"sjxl",
                         @"voice":[[NSBundle bundleWithPath:path]pathForResource:@"山间溪水" ofType:@"mp3"]},
                       @{@"icon":@"bjy",
                         @"title":@"芭蕉叶",
                         @"bigIcon":@"bjy",
                         @"voice":[[NSBundle bundleWithPath:path]pathForResource:@"芭蕉叶" ofType:@"mp3"]},
                       @{@"icon":@"rsz",
                         @"title":@"扔石子",
                         @"bigIcon":@"rsz",
                         @"voice":[[NSBundle bundleWithPath:path]pathForResource:@"扔石子" ofType:@"mp3"]},
                       @{@"icon":@"lyy",
                         @"title":@"雷雨夜",
                         @"bigIcon":@"lyy",
                         @"voice":[[NSBundle bundleWithPath:path]pathForResource:@"雷雨夜" ofType:@"mp3"]},
                       @{@"icon":@"ct",
                         @"title":@"池塘",
                         @"bigIcon":@"ct",
                         @"voice":[[NSBundle bundleWithPath:path]pathForResource:@"池塘" ofType:@"mp3"]},
                      @{@"icon":@"ydblc",
                        @"title":@"雨打玻璃窗",
                        @"bigIcon":@"ydblc",
                        @"voice":[[NSBundle bundleWithPath:path]pathForResource:@"雨打玻璃窗" ofType:@"mp3"]},
              
              @{@"icon":@"smyd",
                @"title":@"水面雨滴",
                @"bigIcon":@"smyd",
                @"voice":[[NSBundle bundleWithPath:path]pathForResource:@"水面雨滴" ofType:@"mp3"]},
              @{@"icon":@"xsmn",
                @"title":@"雪山牦牛",
                @"bigIcon":@"xsmn",
                @"voice":[[NSBundle bundleWithPath:path]pathForResource:@"雪山牦牛" ofType:@"mp3"]},
              @{@"icon":@"yq",
                @"title":@"羊群",
                @"bigIcon":@"yq",
                @"voice":[[NSBundle bundleWithPath:path]pathForResource:@"羊群" ofType:@"mp3"]},
              @{@"icon":@"hojs",
                @"title":@"海鸥礁石",
                @"bigIcon":@"hojs",
                @"voice":[[NSBundle bundleWithPath:path]pathForResource:@"海鸥礁石" ofType:@"mp3"]},
              @{@"icon":@"ab",
                @"title":@"岸边",
                @"bigIcon":@"ab",
                @"voice":[[NSBundle bundleWithPath:path]pathForResource:@"岸边" ofType:@"mp3"]},
              @{@"icon":@"bwfj",
                @"title":@"傍晚飞机",
                @"bigIcon":@"bwfj",
                @"voice":[[NSBundle bundleWithPath:path]pathForResource:@"傍晚飞机" ofType:@"mp3"]},
              @{@"icon":@"qt",
                @"title":@"青苔",
                @"bigIcon":@"qt",
                @"voice":[[NSBundle bundleWithPath:path]pathForResource:@"青苔" ofType:@"mp3"]},
            @{@"icon":@"bsfc",
              @"title":@"白色风车",
              @"bigIcon":@"bsfc",
              @"voice":[[NSBundle bundleWithPath:path]pathForResource:@"白色风车" ofType:@"mp3"]},
            @{@"icon":@"ypm",
              @"title":@"一匹马",
              @"bigIcon":@"ypm",
              @"voice":[[NSBundle bundleWithPath:path]pathForResource:@"一匹马" ofType:@"mp3"]},
            @{@"icon":@"sslf",
              @"title":@"松树林风",
              @"bigIcon":@"sslf",
              @"voice":[[NSBundle bundleWithPath:path]pathForResource:@"松树林风" ofType:@"mp3"]},
            @{@"icon":@"sjsl",
              @"title":@"山间树林",
              @"bigIcon":@"sjsl",
              @"voice":[[NSBundle bundleWithPath:path]pathForResource:@"山间树林" ofType:@"mp3"]},
            @{@"icon":@"sthn",
              @"title":@"沙滩候鸟",
              @"bigIcon":@"sthn",
              @"voice":[[NSBundle bundleWithPath:path]pathForResource:@"沙滩候鸟" ofType:@"mp3"]},
            @{@"icon":@"hhdsy",
              @"title":@"厚厚的树叶",
              @"bigIcon":@"hhdsy",
              @"voice":[[NSBundle bundleWithPath:path]pathForResource:@"厚厚的树叶" ofType:@"mp3"]},
            @{@"icon":@"yuchuanhuigang",
              @"title":@"渔船回港",
              @"bigIcon":@"yuchuanhuigang",
              @"voice":[[NSBundle bundleWithPath:path]pathForResource:@"渔船回港" ofType:@"mp3"]},
            @{@"icon":@"caicha",
              @"title":@"采茶",
              @"bigIcon":@"caicha",
              @"voice":[[NSBundle bundleWithPath:path]pathForResource:@"采茶" ofType:@"mp3"]},
            @{@"icon":@"xiatian",
              @"title":@"夏天",
              @"bigIcon":@"xiatian",
              @"voice":[[NSBundle bundleWithPath:path]pathForResource:@"夏天" ofType:@"mp3"]},
            @{@"icon":@"maitian",
              @"title":@"麦田",
              @"bigIcon":@"maitian",
              @"voice":[[NSBundle bundleWithPath:path]pathForResource:@"麦田" ofType:@"mp3"]},
            @{@"icon":@"fuchuan",
              @"title":@"浮船",
              @"bigIcon":@"fuchuan",
              @"voice":[[NSBundle bundleWithPath:path]pathForResource:@"浮船" ofType:@"mp3"]},
            @{@"icon":@"tuichao",
              @"title":@"退潮",
              @"bigIcon":@"tuichao",
              @"voice":[[NSBundle bundleWithPath:path]pathForResource:@"退潮" ofType:@"mp3"]},
            @{@"icon":@"jianbeike",
              @"title":@"捡贝壳",
              @"bigIcon":@"jianbeike",
              @"voice":[[NSBundle bundleWithPath:path]pathForResource:@"捡贝壳" ofType:@"mp3"]},
            @{@"icon":@"shuidi",
              @"title":@"水滴",
              @"bigIcon":@"shuidi",
              @"voice":[[NSBundle bundleWithPath:path]pathForResource:@"水滴" ofType:@"mp3"]},
            @{@"icon":@"luwei",
              @"title":@"芦苇",
              @"bigIcon":@"luwei",
              @"voice":[[NSBundle bundleWithPath:path]pathForResource:@"芦苇" ofType:@"mp3"]},
              
                             ];
}

+(NSArray *)getAllSecond
{
  return  @[@(300), @(600), @(900), @(1200),
            @(1500),@(1800),@(2100),@(2400),
            @(2700),@(3000),@(3300),@(3600),
            @(3900),@(4200),@(4500),@(4800),
            @(5100),@(5400),@(5700),@(6000),
            @(6300),@(6600),@(6900),@(7200)];
}
@end
